# Generated by Django 5.0.7 on 2024-07-30 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 22, 24, 39, 288928)),
        ),
    ]
