# Generated by Django 5.0.7 on 2024-08-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='time',
        ),
    ]
