# Generated by Django 5.0.7 on 2024-08-21 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_tag_alter_blog_time_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 11, 33, 18, 303007)),
        ),
    ]
