# Generated by Django 5.0.7 on 2024-08-22 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_comments_alter_blog_time_blog_commented_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='commented_by',
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 11, 3, 21, 249902)),
        ),
    ]
