# Generated by Django 5.0.7 on 2024-08-23 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_comments_options_comments_which_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 23, 20, 53, 18, 98257)),
        ),
    ]
