# Generated by Django 5.0.7 on 2024-08-24 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_remove_blog_author_user_email_alter_blog_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='which_post',
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 0, 36, 21, 76145)),
        ),
    ]
