# Generated by Django 5.0.7 on 2024-08-25 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_remove_comments_user_remove_comments_which_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 11, 29, 9, 194847)),
        ),
    ]
