# Generated by Django 5.0.7 on 2024-08-26 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_author_alter_blog_time_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 19, 49, 32, 956872)),
        ),
    ]
